[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
COSMO = "1e616198-aa4e-51ec-90a2-23f7fbd31d8d"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
OpenML = "8b6db2d4-7670-4922-a472-f9537c81ab66"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
